<a href="https://colab.research.google.com/github/AkbarBunyad/Training_Programs/blob/main/gi_group_ds/practice/practice_5_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1: Create a zero vector of size 10 and update the fifth value to 1.

In [ ]:
import numpy as np
vect = np.zeros(10)
vect[4] = 1
print(vect)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a Numpy array filled with numbers from 10 to 49, inclusive, and reverse it (so that the last element becomes the first).

In [ ]:
lst = np.arange(10,50)
print(lst[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


3.Create a 3x3 identity matrix

In [ ]:
#3 by 4 identity matrix
#np.identity(3)

m = [[0 for x in range (3)] for y in range (3)]
for i in range (3):
  for j in range(3):
    if i ==j:
      m[i][j] = 1
np.array(m)


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

4.Create a 3x3 array with values ranging from 0 to 8.

In [ ]:
c = 0
lst = [[], [], []]
for i in range(3):
  for j in range(3):
    lst[i].append(c)
    c+=1
print(lst)

print(np.arange(0, 9).reshape(3, 3))

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


5.Create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
l = np.random.randint(0, 100, (10, 10))
print(l)
print(np.max(l))
print(np.min(l))


[[ 9 43 75 57  3 34 62 33 33 90]
 [53 36 70 13 21 94 40 91 18 98]
 [60 39  2 71 10 71 33 50 84 86]
 [18 28 96  6 43 64 24  7 35  7]
 [16 44 73  8  3 39  1 55 45 77]
 [98 51 73 41 30 70 98 65  1 22]
 [72 15 50 38 93 83 91 92 46  2]
 [82 59 60 28 94 49 60 18 60 91]
 [96 57 19 43 82 94 53 44  4 93]
 [33 16 43 33 54 72 77 72 21 17]]
98
1


6.Find the mean value of a random array of 30 elements.

In [ ]:
arr = np.random.rand(30)
print(arr)
print(np.mean(arr))

[0.81863152 0.34384031 0.36434918 0.12150352 0.2250312  0.70297485
 0.52104781 0.86287983 0.23446914 0.68652944 0.4512006  0.59279492
 0.82728239 0.5562768  0.02733198 0.87849869 0.63883709 0.35550771
 0.47402893 0.39832341 0.35384067 0.14502702 0.15154866 0.50093733
 0.22595882 0.45457016 0.38915473 0.83394098 0.95481322 0.0657839 ]
0.4718971599862972


7.Create a 2D array of shape (5,5) with values 1,2,3,4 just below the diagonal.

In [ ]:
l = np.zeros((5, 5))
for i in range (5):
  l[i, i-1] = i
print(l)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


8.Normalize a 5x5 random matrix (subtract the mean and divide by the standard deviation).

In [ ]:
arr = np.random.randint(1, 45, (5, 5))
print(arr)
updated = (arr - np.mean(arr))/np.std(arr)
print(updated)

[[31 35 20 41 37]
 [16 31  9 31  6]
 [24 32 27 44 31]
 [ 7  6  7 18 11]
 [30 15 37 14  5]]
[[ 0.69216144  1.02176212 -0.21424044  1.51616314  1.18656246]
 [-0.54384113  0.69216144 -1.12064232  0.69216144 -1.36784284]
 [ 0.11536024  0.77456161  0.36256075  1.76336366  0.69216144]
 [-1.28544267 -1.36784284 -1.28544267 -0.37904079 -0.95584198]
 [ 0.60976126 -0.6262413   1.18656246 -0.70864147 -1.45024301]]


9.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [ ]:
arr1 = np.random.randint(1, 10, (5, 3))
arr2 = np.random.randint(5, 14, (3, 2))
f = np.dot(arr1, arr2)
print(arr1)
print(arr2)
print(f)

[[8 9 7]
 [9 5 8]
 [4 6 3]
 [9 7 7]
 [9 6 3]]
[[13 13]
 [ 5 12]
 [12 10]]
[[233 282]
 [238 257]
 [118 154]
 [236 271]
 [183 219]]


10.Subtract the mean of each row of a matrix (use a 10x10 matrix).

In [ ]:
np.random.seed(34)
arr = np.random.randint(1, 10, (10, 10))
l = np.mean(arr, axis  = 1)
print(arr)
print(l)
print(arr - l)

[[2 7 6 5 4 6 3 9 7 6]
 [7 5 6 1 6 5 4 4 6 6]
 [9 9 5 9 5 3 6 3 3 7]
 [9 3 7 1 6 5 1 5 5 8]
 [5 8 4 7 8 7 9 9 5 5]
 [1 2 2 6 4 6 1 1 3 4]
 [5 2 9 7 8 4 7 6 2 7]
 [2 1 6 7 8 2 7 8 3 6]
 [3 1 2 6 7 5 3 2 1 9]
 [9 8 7 8 3 5 7 7 5 1]]
[5.5 5.  5.9 5.  6.7 3.  5.7 5.  3.9 6. ]
[[-3.5  2.   0.1  0.  -2.7  3.  -2.7  4.   3.1  0. ]
 [ 1.5  0.   0.1 -4.  -0.7  2.  -1.7 -1.   2.1  0. ]
 [ 3.5  4.  -0.9  4.  -1.7  0.   0.3 -2.  -0.9  1. ]
 [ 3.5 -2.   1.1 -4.  -0.7  2.  -4.7  0.   1.1  2. ]
 [-0.5  3.  -1.9  2.   1.3  4.   3.3  4.   1.1 -1. ]
 [-4.5 -3.  -3.9  1.  -2.7  3.  -4.7 -4.  -0.9 -2. ]
 [-0.5 -3.   3.1  2.   1.3  1.   1.3  1.  -1.9  1. ]
 [-3.5 -4.   0.1  2.   1.3 -1.   1.3  3.  -0.9  0. ]
 [-2.5 -4.  -3.9  1.   0.3  2.  -2.7 -3.  -2.9  3. ]
 [ 3.5  3.   1.1  3.  -3.7  2.   1.3  2.   1.1 -5. ]]


11.Create a 4x4 matrix with values from 0 to 15, and then replace any value that is greater than 5 with the value -1.

In [ ]:
l = np.arange(0, 16).reshape(4, 4)
print(l)
l[l>5] = -1
c = np.copy(l)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


12.Create a 30x30 matrix with random values and find the maximum value in each row.

In [ ]:
lst = np.random.randint(1, 200, (30, 30))
print(lst)
up = np.max(lst, axis = 1)
print(up)

[[ 77  85  88 172  81  83  87  43  18 143  15  87 141  84  91  84 137  29
   54 198 186 109 172  82 102  18 184  95 165 132]
 [114  13 116 156  52 119  78  81  39  40 168  77 120  44 193  49 176 121
  189  78  72  89 190  86   3 127  88 167  16 175]
 [153 159 190   7  26  23  56  56 140  66  90  80 122 186 101  99 140  65
  187  43  58  28 119 123  92 166  23 167  94  16]
 [164   1  67  80  54 193 130  59 183 167 145 189 100  87  95 130 178 193
  135 145  31  17  20 163 185 186 101 125 102  17]
 [196  14  75 171 109 178  87 144  46  22  59  89 123   5  99 162 118 185
   91  47 173  86  26  38 154   2 109  39 159 130]
 [ 16  82 184  36 118 170 159 156 167  44  84  46 129  62  84  40  78 123
   72  35 190  85  43 126  86  88  57  66 131  58]
 [187  96  40 114 138 105  17  42  32  86  13 190   2  54  61 169 102 143
   69 185  23 102  10 139  34  69 173 133 145  64]
 [ 50 151  84  90  70 122 180 128 160  25 165 128 141  98   3  78 115  25
  188 147  90  11   2  24 189  76 138  55  44 167]


13.Create a random vector of size 100 and find the position of the maximum value

In [ ]:
s = np.random.randint(1, 100, (100))
print(s)
#np.argmax(s)
mx = s[0]
for i in range(len(s)):
  if mx < s[i]:
    mx = s[i]
    idx = i
print(mx)
print(idx)

[77  3 54 91  2 39 21 15 88 25 45 82 87 77 90 68  5 55 29 53 20 37 75 10
 31 93 40 75 28 56  5  4 87 57 26 85 17 53 36 16 32 58 16 79 37 99  9 38
 15 39 58 16 21 64 83 42  2 32 40 12 87 26  2 87 88 74 53 63 68  6 44 88
 44 41 25 99 55 91 72 77 52 86  2 88 13 20  1 15 46 96 35 33 15 48 16 77
 59 88 86 83]
99
45
