<a href="https://colab.research.google.com/github/AkbarBunyad/Training_Programs/blob/main/gi_group_ds/assignments/Small_Homework_7_(Scholarship).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Good luck!

**Import numpy library.**

**1. Create an array of ones in (3,3) shape.**  (Vahid matris)

In [ ]:
import numpy as np
m = [[0 for x in range(3)] for y in range(3)]
for i in range (3):
  for j in range (3):
    if i == j:
      m[i][j] = 1
np.array(m)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**2. Create an array of random values in (4,4) shape.**

In [ ]:
mt = np.random.rand(4, 4)
mt

array([[0.90991589, 0.32480162, 0.0914055 , 0.63196233],
       [0.60933265, 0.12600642, 0.51661528, 0.14597898],
       [0.67424243, 0.82425338, 0.20237434, 0.26408865],
       [0.72103323, 0.66984377, 0.38368163, 0.64693644]])

**3. Insert 55 to this array at position 3: arr = np.array([76,23,19,45]).**

In [ ]:
arr = np.array([76, 23, 19, 45])
arr = np.insert(arr, 2, 55)
arr

array([76, 23, 55, 19, 45])

**4. Copy this array as a different name and delete the element 19 from this array(copy).**

In [ ]:
arr1 = arr.copy()
arr1 = np.delete(arr1, np.where(arr1 == 19))
arr1

array([ 1.,  2.,  3.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])

**5. Create a new array that contains only the elements of arr5 that are greater than 9 and less than 20.**

In [ ]:
arr5 = np.arange(25).reshape(5, 5)
new = arr5[(arr5 > 9) & (arr5<20)]
new

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

**6. Convert the list [12, 42, 13] and [81, 26, 70] to numpy arrays arr1 and arr2. Then perform Addition , Subtraction , Multiplication and Division Operation on the arr1 and arr2.**

In [ ]:
arr1 = np.array([12, 42, 13])
arr2 = np.array([81, 26, 70])
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2
print('addition: ', addition)
print('subtraction: ', subtraction)
print('multiplication: ', multiplication)
print('division: ', division)

addition:  [93 68 83]
subtraction:  [-69  16 -57]
multiplication:  [ 972 1092  910]
division:  [0.14814815 1.61538462 0.18571429]


**7. Find the sum of maximum and minimum value in the given numpy array:
a = np.array([15, 20, 23, 44, 98])**

**(Output 113)**

In [ ]:
arr = np.array([15, 20, 23, 44, 98])
'''max_val = np.max(arr)
min_val = np.min(arr)
print('sum of maximum and minimum value: ', max_val + min_val)'''

max_val = arr[0]
min_val = arr[0]
for i in arr:
  if i > max_val:
    max_val = i
  if i < min_val:
    min_val = i
print('sum of maximum and minimum value: ', max_val + min_val)

sum of maximum and minimum value:  113


**8. Convert the list [1, 2, 3, 4, 5] to numpy array arr1. Then find the even and odd numbers from arr1.**


**(Output even for array1 [2 4]**


**odd for array1 [1 3 5])**

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
even_l = arr1[arr1 % 2 == 0]
odd_l = arr1[arr1 % 2  == 1]
print(even_l)
print(odd_l)

[2 4]
[1 3 5]
